### ISSUE TITLE
Updating vehicle_signal_specification to use the latest vss-tools master, make fails:

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vss-tools#11]
Attempting to update to the latest master commit of vss-tools, running make inside VSS causes the following for me:

... (successful parts removed) ...

```
cd vehicle_signal_specification
   (update submodule)
make
...
./vss-tools/vspec2json.py -i:spec/VehicleSignalSpecification.id -I ./spec ./spec/VehicleSignalSpecification.vspec vss_rel_$(cat VERSION).json
Traceback (most recent call last):
  File "./vss-tools/vspec2json.py", line 14, in <module>
    import vspec
  File "/tmp/a/vehicle_signal_specification/vss-tools/vspec.py", line 17, in <module>
    from anytree import (Resolver, ChildResolverError, LevelOrderIter)
ModuleNotFoundError: No module named 'anytree'
make: *** [Makefile:15: json] Error 1
```

Hmm... but **anytree** seems to be installed using pip already?
However, it's in /usr/**local**/lib/python3.7/site-packages

Is this a local problem only for me?  Please confirm.

Of course I could send a PR with an update and vehicle_signal_specification should run the automated build checks, but probably someone with more knowledge can comment on the above --> @Floix?  @magnusfeuer what is your experience?

==> So what is required to make it work - a code change or instructions in a README for how to install the right prerequisites?

**Comment by chrizmc** [comment]
Some time ago I had a similar problem. I changed the first line of the file from

#!/usr/bin/python3

to 

#!/usr/local/bin/python3

Then it should work.

**Comment by SebastianSchildt** [comment]
I will check

**Comment by Floix** [comment]
> Some time ago I had a similar problem. I changed the first line of the file from
> 
> #!/usr/bin/python3
> 
> to
> 
> #!/usr/local/bin/python3
> 
> Then it should work.

Is there a better way to remove/reduce the dependency to dev machine settings? E.g., just execute python without absolute paths or a build container?

**Comment by gunnarx** [comment]
> Is there a better way to remove/reduce the dependency to dev machine settings? E.g., just execute python without absolute paths or a build container?

@chrizmc, Yes I agree with @Floix.  I asked for guidance precisely because I don't want to just "make it work on my machine".   We need to decide on a strategy, with possibly a specific environment that is the supported one.  I noticed more path/version issues in the Travis environment, documented in #12

**Comment by SebastianSchildt** [comment]
I would just clearly state it needs python3, i.e. change "python" to python3" in the Readme. And probably get rid of the Makefile.

For me it was a matter to pip3 install the missing dependencies one by one (but others might orefer to apt install where available or install locally) . It is hard to do that machine independently.  

One way to make it a little more generic would be a using pipenv. See here https://github.com/eclipse/kuksa.val/tree/master/vss-testclient the [README](https://github.com/eclipse/kuksa.val/blob/master/vss-testclient/README.md) and [Pipfile](https://github.com/eclipse/kuksa.val/blob/master/vss-testclient/Pipfile) . This would describe Python version dependency and required python packages as unambiguously as we want and let pipenv figure out the rest.

**Comment by danielwilms** [comment]
> And probably get rid of the Makefile.

but it's not a matter of the makefile, is it?

> For me it was a matter to pip3 install the missing dependencies one by one 

For me it worked installing the missing dependencies with the requirements-file

**Comment by danielwilms** [comment]
> Is there a better way to remove/reduce the dependency to dev machine settings? E.g., just execute python without absolute paths or a build container?

`#!/usr/bin/env python3` should solve the specific issue.

**Comment by gunnarx** [comment]
Thanks for your input.  It works also locally for me, with my latest changes (using env and specifying python3) in PR 19.   I expect there is no more to add on this now so I will close this.

Mostly I was uncertain if there was an officially recommended way.  
From the #python irc channel, someone confirmed to me that it should be expected that Linux distros always have "python3" resolving OK, even if "python" has been changed to v3 already.  So based on that I agree we should do this.
