### ISSUE TITLE
vspec2c not supporting array datatypes

### ISSUE THREAD

**Issue by SebastianSchildt** [GENIVI/vss-tools#14]
As discovered here https://github.com/GENIVI/vehicle_signal_specification/pull/177  the vspec2c generator does not support arrays

**Comment by danielwilms** [comment]
@magnusfeuer: Could you please have a look.

**Comment by danielwilms** [comment]
@danielwilms has a look

**Comment by s-e-martin** [comment]
JLR moves to deprecate `vspec2c` unless somebody else needs it (see https://github.com/GENIVI/vss-tools/issues/23#issuecomment-700876515)
