### ISSUE TITLE
Protobuf broken due to move to contrib

### ISSUE THREAD

**Issue by SebastianSchildt** [GENIVI/vss-tools#50]
I think the move to contrib killed protobuf 

```
make protobuf
./vss-tools/contrib/vspec2protobuf.py -i:spec/VehicleSignalSpecification.id -I ./spec ./spec/VehicleSignalSpecification.vspec vss_rel_$(cat VERSION).proto
Traceback (most recent call last):
  File "./vss-tools/contrib/vspec2protobuf.py", line 13, in <module>
    import vspec
ModuleNotFoundError: No module named 'vspec'
make: *** [Makefile:37: protobuf] Error 1
```

I think we need to change the search path for python includes to include ../ , anyway, just writing this issue for ow, so we do not forget

**Comment by erikbosch** [comment]
Has it been anywhere else? We added make support in https://github.com/GENIVI/vehicle_signal_specification/commit/309a96936f3cdf9a6b117ce06e7b0e93be48b652 and already then it was part of contrib.

Anyhow - I am considering if a move of Makefile to vss-tools would make sense to simplify fixing make problems without getting a lot of dependencies, see: https://github.com/GENIVI/vehicle_signal_specification/issues/264

You can fix the build by adding `PYTHONPATH=${TOOLSDIR}` in the Makefile command for protobuf, see https://github.com/GENIVI/vehicle_signal_specification/pull/260/files 

`PYTHONPATH=./vss-tools ./vss-tools/contrib/vspec2protobuf.py -i:spec/VehicleSignalSpecification.id -I ./spec ./spec/VehicleSignalSpecification.vspec vss_rel_$(cat VERSION).proto`

**Comment by erikbosch** [comment]
Can be closed now I think
