### ISSUE TITLE
Structure of tool documentation

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vss-tools#60]
As of today the tools in this repo have very limited documentation. There is some usage information in some of the python files, and some in the README (partially outdated), but it is difficult to get an overview, and there is no documentation on e.g. the output produced by vspec2csv, and limitations (if any) in the tools.

I think it would be good to improve the documentation, some ideas:

- Each tool (at least those outside contrib) shall have a separate *.md file (in the same directory as the *.py file) giving a short overview of what the tool does and how the output will look like and can be used, as well as known limitation with the tool. 
- The main README.md shall reference all tool subpages

With this it would be quite easy to state that e.g. vspec2protobuf will ignore arraysize, as protobuf does not have any concept for that. Any opinion?

**Comment by danielwilms** [comment]
Goal: Create a `README.md` for each tool and create a separate folder for each of them along with the documentation
