### ISSUE TITLE
Use of uuid_file in tools?

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vss-tools#65]
How is `-i` supposed to be used? Most tools seems to require it even if some state that is optional. I have not really found any good description with examples, especially how prefix and multiple use of  `-i` are supposed to be used. Should we possibly create some documentation on why it is needed and how it can be used, possibly as part of common documentation of vss-tools.

```
 -i prefix:uuid_file  "prefix" is an optional string that will be
                       prepended to each signal name defined in the
                       vspec file.

                       "uuid_file" is the name of the file containing the
                       static UUID values for the signals.  This file is
                       read/write and will be updated if necessary.

                       This option can be specified several times in
                       to store the UUIDs of different parts of the
                       signal tree in different files.
```

**Comment by danielwilms** [comment]
way forward:
1. Fix documentation
2. Rethink if mandatory parameter is needed

**Comment by erikbosch** [comment]
Proposal to remove it exists in following PRs

Removal of parameter support: https://github.com/GENIVI/vss-tools/pull/69 
Makefile and submodule adaption: https://github.com/GENIVI/vehicle_signal_specification/pull/298

**Comment by SebastianSchildt** [comment]
As the PR is merged this can be closed @erikbosch  @gunnarx
