### ISSUE TITLE
constants.py maps UINT64 to (signed) Int64?

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/vss-tools#8]
As noted, this comment was never clarified.  
https://github.com/GENIVI/vss-tools/pull/7#discussion_r447283118

We discussed a similar issue in https://github.com/GENIVI/vehicle_signal_specification/issues/163
but so far there is no decision to map UInt to Int... so we have to consider the line at location:
https://github.com/GENIVI/vss-tools/blob/4497a47626867f805c62d082ecc68e292a93bf65/model/constants.py#L125
to be a bug?

**Comment by SebastianSchildt** [comment]
@Floix can you check? Is it a typo?

**Comment by Floix** [comment]
@SebastianSchildt yes, that is a typo. Sorry about that.
PR is ready for review an merge: https://github.com/GENIVI/vss-tools/pull/13

**Comment by danielwilms** [comment]
@gunnarx: to be closed

**Comment by danielwilms** [comment]
related to #239, need mentions in the documentation as well.
