### ISSUE TITLE
Use of DEFAULT_SEPARATOR in detect_and_merge

### ISSUE THREAD

**Issue by oliveirarleo** [GENIVI/vss-tools#82]
In these two lines of code
https://github.com/GENIVI/vss-tools/blob/14d044699bc358590009aaf1740864c149d3c9be/vspec/__init__.py#L748
https://github.com/GENIVI/vss-tools/blob/14d044699bc358590009aaf1740864c149d3c9be/vspec/__init__.py#L752

The method `qualified_name()` is used without any parameter, so it uses the `DEFAULT_SEPARATOR`, [which is the character "."](https://github.com/GENIVI/vss-tools/blob/7e36e5a357d276e2a25f273b7774f6b5e4c1eddd/vspec/model/vsstree.py#L21), but when r.get is called with the `qualified_name` with the separator `"."` it returns an error, as the following example:
`anytree.resolver.ResolverError: unknown root node '/Vehicle.Private.Lifecycle'. root is '/Vehicle'.`
because the resolver tries to split the string as nodes with the separator `"/"` by default. 

A simple way to detect this is in these two lines:
https://github.com/GENIVI/vss-tools/blob/14d044699bc358590009aaf1740864c149d3c9be/vspec/__init__.py#L748-L749
The line 784 uses the `qualified_name()` with the `DEFAULT_SEPARATOR` and then try to remove the string `"/Private"` which can only exists if the `DEFAULT_SEPARATOR` is `"/"` or if you call `qualified_name("/") `

**Comment by SebastianSchildt** [comment]
Can you elaborate how this error can be triggered with current tools? (obviously "just" compiling standard catalogue with default settings is no problem)

Some example  input/parameters to make it easier for reviewers to test the fix in #83

**Comment by oliveirarleo** [comment]
Try changing 

https://github.com/GENIVI/vss-tools/blob/14d044699bc358590009aaf1740864c149d3c9be/vspec2json.py#L109-L110

to `tree = vspec.load_tree(args[0], include_dirs, exclude_private=True, break_on_noncore_attribute=strict)`

And then on [Private.vspec](https://github.com/GENIVI/vehicle_signal_specification/blob/baf055ba7233fe5ad2911a6079a456e78feb3c2a/spec/Private/Private.vspec) add the line `#include CARFIT/Signal.vspec`.

If you run with `python vspec2json.py -I path/to/spec VehicleSignalSpecification.vspec a.json`

You will get `anytree.resolver.ResolverError: unknown root node '/Vehicle.Private.Vehicle'. root is '/Vehicle'`.
