### ISSUE TITLE
Why there is no vspec2yaml?

### ISSUE THREAD

**Issue by crea7or** [GENIVI/vss-tools#95]
Although vspec is almost yaml, it looks like it will be useful to supply vss tree as yaml. It's cleaner than json and better in some small usage patterns regarding c++ libraries that process json/yaml. I'm thinking about developing such script but maybe there some limitation of yaml that I don't know or not understand.

**Comment by SebastianSchildt** [comment]
If you think about a way to generate a "flattened" single-file YAML version out of the existing vspec, that is indeed missing currently. I do think that would not be too hard to create based on the tooling available (check vspec2json or vspec2csv maybe it is as simple as just rewriting the export_node https://github.com/GENIVI/vss-tools/blob/865ea7c06c98f73f5ea724aa19a39ee6e12ae1ba/vspec2json.py#L33 function?)

If you try, pls make a PR :)

**Comment by gunnarx** [comment]
I propose the discussion continues on the now existing PR (only)
